name: Build Android APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install npm dependencies
        run: npm install

      - name: Build web assets
        run: npm run build

      - name: Install Capacitor dependencies
        run: npm install @capacitor/core @capacitor/cli @capacitor/android

      - name: Initialize Capacitor if needed
        shell: bash
        run: |
          if [ ! -f capacitor.config.json ]; then
            npx cap init "MacroTracking" "com.fmode.macrotracking"
          else
            echo "Capacitor config exists, skipping init"
          fi

      - name: Add Android platform if missing
        shell: bash
        run: |
          if [ ! -d android ]; then
            npx cap add android
          else
            echo "Android platform exists, skipping add"
          fi

      - name: Copy web assets to Android
        run: npx cap copy android

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build Android APK
        shell: bash
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
