name: Build Android APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install @capacitor/core @capacitor/cli @capacitor/android --save-dev

      - name: Build web assets
        run: npm run build

      - name: Ensure Capacitor config exists
        run: |
          if [ ! -f capacitor.config.json ]; then
            npx cap init "MacroTracking" "com.fmode.macrotracking"
          fi

      - name: Add Android platform
        run: npx cap add android || echo "Android platform exists"

      - name: Copy web assets to Android
        run: npx cap copy android

      - name: Make Gradle executable
        run: chmod +x android/gradlew

      - name: Build APK
        run: ./android/gradlew assembleDebug
