name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build web assets
        run: npm run build

      - name: Install Capacitor CLI
        run: npm install @capacitor/cli @capacitor/core @capacitor/android --save-dev

      - name: Add Android platform (skip if exists)
        run: |
          if [ ! -d "android" ]; then
            npx cap add android
          else
            echo "Android platform exists"
          fi

      - name: Copy web assets to Android
        run: npx cap copy android

      - name: Make Gradle executable
        run: chmod +x android/gradlew

      - name: Build APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
