name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js with caching
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      # 3. Install Node dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # 4. Build web assets
      - name: Build web assets
        run: npm run build

      # 5. Install Capacitor CLI & Android
      - name: Install Capacitor CLI & Android
        run: npm install @capacitor/core @capacitor/cli @capacitor/android --save-dev

      # 6. Setup Java 17 for Android build
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
          cache: gradle

      # 7. Prepare Android platform
      - name: Prepare Android platform
        run: |
          npx cap sync android
          chmod +x android/gradlew

      # 8. Clean previous Android builds (optional but recommended)
      - name: Clean Android build
        working-directory: android
        run: ./gradlew clean

      # 9. Build APK
      - name: Build APK
        working-directory: android
        run: ./gradlew assembleDebug --no-daemon

      # 10. Upload APK artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
