name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install NPM dependencies
        run: npm install --legacy-peer-deps

      - name: Build web assets
        run: npm run build

      - name: Install Capacitor
        run: npm install @capacitor/cli @capacitor/core @capacitor/android --save-dev

      - name: Ensure Android platform
        run: |
          if [ ! -d "android" ]; then
            npx cap add android
          fi

      - name: Copy Capacitor web assets
        run: npx cap copy android

      - name: Remove Cordova references
        run: |
          sed -i '/cordova.variables.gradle/d' android/app/capacitor.build.gradle

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build Android APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
