name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install NPM packages
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Install Capacitor & Android
        run: |
          npm install @capacitor/core @capacitor/cli @capacitor/android
          if [ ! -f capacitor.config.ts ]; then
            npx cap init app com.example.app --web-dir=dist
          fi
          npx cap add android || echo "Android platform already added"
          npx cap copy

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
